// Generated by CoffeeScript 1.7.1

/*
Arcade Royale Launcher
Hello hello. 2014.
MIT License.
 */
var ext, file, filenames, fs, game, games, helpers, k, k2, keys, path, settings, v, v2, _i, _j, _len, _len1, _ref,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

fs = require('fs');

helpers = require('./js/helpers');

settings = JSON.parse(fs.readFileSync('../settings.json'));

settings.leftColour = helpers.hexToHsl(settings.leftColour);

settings.rightColour = helpers.hexToHsl(settings.rightColour);

keys = settings.keys;

for (k in keys) {
  v = keys[k];
  if (typeof v === "object") {
    for (k2 in v) {
      v2 = v[k2];
      if (helpers.keyNameToCode[v2] !== void 0) {
        keys[k][k2] = helpers.keyNameToCode[v2];
      } else {
        console.log("Unknown key: '" + v2 + "'");
      }
    }
  } else {
    if (helpers.keyNameToCode[v] !== void 0) {
      keys[k] = helpers.keyNameToCode[v];
    } else {
      console.log("Unknown key: '" + v + "'");
    }
  }
}

keys.anyLeft = (function() {
  var _results;
  _results = [];
  for (k in keys) {
    v = keys[k];
    if (v.left !== void 0) {
      _results.push(v.left);
    }
  }
  return _results;
})();

keys.anyRight = (function() {
  var _results;
  _results = [];
  for (k in keys) {
    v = keys[k];
    if (v.right !== void 0) {
      _results.push(v.right);
    }
  }
  return _results;
})();

keys.anyA = (function() {
  var _results;
  _results = [];
  for (k in keys) {
    v = keys[k];
    if (v.a !== void 0) {
      _results.push(v.a);
    }
  }
  return _results;
})();

keys.anyB = (function() {
  var _results;
  _results = [];
  for (k in keys) {
    v = keys[k];
    if (v.b !== void 0) {
      _results.push(v.b);
    }
  }
  return _results;
})();

games = [];

filenames = fs.readdirSync(settings.baseDirectory);

for (_i = 0, _len = filenames.length; _i < _len; _i++) {
  file = filenames[_i];
  path = settings.baseDirectory + file;
  if (fs.statSync(path).isDirectory()) {
    if (fs.existsSync(path + '/arcadedata.json')) {
      game = JSON.parse(fs.readFileSync(path + '/arcadedata.json'));
      _ref = ['png', 'gif', 'jpg'];
      for (_j = 0, _len1 = _ref.length; _j < _len1; _j++) {
        ext = _ref[_j];
        if (fs.existsSync(path + '/screenshot.' + ext)) {
          game.screenshot = path + '/screenshot.' + ext;
          break;
        }
      }
      games.push(game);
    } else {
      console.log("Warning: no arcade data file found at " + path);
    }
  }
}

games.sort(function(a, b) {
  if (a.title > b.title) {
    return 1;
  }
  if (a.title < b.title) {
    return -1;
  }
  return 0;
});

$(function() {
  var col, i, la, style, t, _k, _len2;
  for (i = _k = 0, _len2 = games.length; _k < _len2; i = ++_k) {
    game = games[i];
    $("#mainContainer ol").append("<li id=\"slide" + i + "\">\n    <h2><span>" + game.title + "</span></h2>\n    <div class=\"slidecontent\">\n        <h1>" + game.description + "</h1>\n        <h1>" + game.description_fr + "</h1>\n    </div>\n</li>");
    if (game.screenshot !== void 0) {
      $("#slide" + i + " .slidecontent").append("<img src=\"" + game.screenshot + "\">");
    }
  }
  style = (function() {
    var _l, _ref1, _results;
    _results = [];
    for (i = _l = 0, _ref1 = games.length; 0 <= _ref1 ? _l <= _ref1 : _l >= _ref1; i = 0 <= _ref1 ? ++_l : --_l) {
      t = i / games.length;
      col = helpers.hslLerp(settings.leftColour, settings.rightColour, t);
      _results.push("#slide" + i + " h2 { background-color: hsl(" + col.h + ", " + col.s + "%, " + col.l + "%) }\n#slide" + i + " div { background-color: hsl(" + col.h + ", " + col.s + "%, " + col.l + "%) }");
    }
    return _results;
  })();
  $("head").append("<style>" + style.join("\n") + "</style>");
  la = $("#mainContainer").liteAccordion({
    "easing": "easeOutCubic",
    "containerWidth": $(window).width(),
    "containerHeight": $(window).height(),
    "headerWidth": 80,
    "slideSpeed": 400
  }).data('liteAccordion');
  return $(document).keydown(function(e) {
    var _ref1, _ref2, _ref3, _ref4;
    if (e.which === keys.home) {
      la.play(0);
      return la.stop();
    } else if (_ref1 = e.which, __indexOf.call(keys.anyLeft, _ref1) >= 0) {
      return la.prev();
    } else if (_ref2 = e.which, __indexOf.call(keys.anyRight, _ref2) >= 0) {
      return la.next();
    } else if ((_ref3 = e.which, __indexOf.call(keys.anyB, _ref3) >= 0) || (_ref4 = e.which, __indexOf.call(keys.anyA, _ref4) >= 0)) {
      if (la.current() !== 0) {
        return console.log("ok!");
      }
    }
  });
});

//# sourceMappingURL=main.map
